export const INJECTION_TOKEN = {
  CHANNEL_WALLET: "CHANNEL_WALLET",
  MESSAGING_SERVICE: "MESSAGING_SERVICE",
  MESSAGE_ROUTER: "MESSAGE_ROUTER",
  CONFIG_SERVICE: "CONFIG_SERVICE",
  WALLET_RPC_SERVICE: "WALLET_RPC_SERVICE",
};
